### ISSUE TITLE
footnotes stop working, when using glossarify

### ISSUE THREAD

**Issue by MrGung** [about-code/glossarify-md#38]
Hi,

I am using vuepress 1.1.0 with markdown-it-footnote 3.0.2.

When activating glossarify (2.0.0) - footnotes stop working, i.e. `[^footnote1]` is displayed verbatim instead of being a link.

**Comment by about-code** [comment]
I suspect what causes the references to be displayed verbatim is the fact that the markdown AST stringifier [remark-stringify](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify) used internally translates the colon of the footnote into an HTML entity sequence, so  instead of 

```
This is a text with a footnote [^footnote].

[^footnote]: This is correct
```

it renders

```
This is a text with a footnote [^footnote].

[^footnote]&#x3A; This is wrong
```
I played around with the respective *remark-stringify* options `options.gfm` and `options.entities` with no success so far. Part of the problem could be that there is no distinct representation of footnotes in the AST produced by [remark-parse](https://github.com/remarkjs/remark/tree/master/packages/remark-parse) which adheres to the [CommonMark Specfication](https://spec.commonmark.org/current/). This spec, which is currently at v0.29, doesn't specify footnotes, so they must be considered custom markdown extensions of the *markdown-it* toolsuite used with *vuepress*.

This is not to say it's impossible to solve but just to provide a bit more context to the issue and why footnotes do not work out of the box at the moment.

**Comment by about-code** [comment]
Okay turned out to be easier than expected. After a look at the source files I found that [remark-parse](https://github.com/remarkjs/remark/tree/master/packages/remark-parse) and [remark-stringify](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify) both already implement support for footnotes but the feature must be enabled explicitely with the parser and `options.footnotes` (instead of the stringifier where I looked first). 

Since they are not yet officially part of the CommonMark Spec *glossarify-md v2.1.0* will also require explicit feature toggling by a separate boolean config option `experimentalFootnotes`. When set to true footnotes will be rendered  according to [Pandoc](https://pandoc.org/MANUAL.html#footnotes) syntax as expected by [markdown-it-footnote](https://github.com/markdown-it/markdown-it-footnote#readme).

**Comment by MrGung** [comment]
Thanks for the ultra fast fix. I'll bump up the Version on monday.

**Comment by MrGung** [comment]
Works! Thanks!
