### ISSUE TITLE
Unclear how to disable reportNotMentioned

### ISSUE THREAD

**Issue by moltar** [about-code/glossarify-md#67]
It seems to be `true` by default. But there is no config option to disable that. And the command line flag appears to be a boolean flag, which has no negative option (e.g. `--no-reportNotMentioned`).

My use case is to generate a glossary of terms, but there isn't any body of text attached to the terms. It's a set of industry terms that organization member should be familiar with, but not necessarily included into any text.

Thanks.

**Comment by about-code** [comment]
@moltar Thank you for your interest in glossarify-md and reporting this. The implementation has been ignoring the option completely and just used the default of `true` from the libraries internal config schema.

This will be fixed with release of `v3.3.0`. Reporting on terms not being mentioned anywhere is now off by default and must be enabled explicitely, either with `reportNotMentioned` provided on command line or in config file. While this may look like a breaking change I don't think it is, because reporting is just informal behavior. Everything else continues to work as expected and the fix eventually makes things work as promised.
