### ISSUE TITLE
Cannot find module 'remark-stringify'

### ISSUE THREAD

**Issue by Fischermaen** [about-code/glossarify-md#87]
I've updated to v.3.6.0 in my VuePress driven documentation. Trying to call "npm run glossarify" results in error message stated above. I could help myself with installing module "remark-stringify".

Error log attached.
[error-log.txt](https://github.com/about-code/glossarify-md/files/4508181/error-log.txt)

**Comment by about-code** [comment]
Hi @Fischermaen. Sorry for the late response. Do you have used markdown-formatted headlines somewhere, for example Headlines with a codespan? Then the issue is likely the same as https://github.com/about-code/glossarify-md/issues/75.

In `master` branch glossarify-md has already been made more robust with respect to using markdown formattings in headlines or anchors etc. I will release it immediately as v3.6.1.

**Comment by about-code** [comment]
I've released v3.6.1 just now. Please, try updating and let me know if this fixes the issue for you.
